Сделаны задания 4,5 модуля
js-tasks-ru/jsbasic-20220418-2_garrus pull request #5
Opened 2022-05-02 17:50 UTC by egor50123

2022-05-02 17:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-04 05:29 UTC, SinimaWath requested changes

2022-05-04 05:29 UTC, SinimaWath commented on 5-module/1-task/index.js
> +    let btn = e.target.closest(".hide-self-button");
Нет необходимости здесь использовать делегирование.

Проще/эффективней повесить обработчик события сразу на `.hide-self-button`

2022-05-04 05:29 UTC, SinimaWath commented on 5-module/2-task/index.js
> +  document.body.addEventListener("click", (e) => {
Нет необходимости здесь использовать делегирование.

Проще/эффективней повесить обработчик события сразу на `.toggle-text-button`

2022-05-04 05:29 UTC, SinimaWath commented on 5-module/2-task/index.js
> +      }
Можно упростить до: `text.hidden = !text.hidden`

2022-05-04 10:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-08 16:07 UTC, SinimaWath approved these changes

2022-05-08 16:09 UTC, merged