Сделаны задачи 6-ого модуля
js-tasks-ru/jsbasic-20220418-2_garrus pull request #6
Opened 2022-05-10 13:31 UTC by egor50123

2022-05-10 13:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-13 14:17 UTC, SinimaWath requested changes

2022-05-13 14:17 UTC, SinimaWath commented on 6-module/3-task/index.js
> +        //slideWidth = document.querySelector(".container").offsetWidth;
Потому что надо выбирать `.container`  - относительно контейнера, а не документа.

Так как твою карусель, могли еще не вставить в DOM

2022-05-13 14:17 UTC, SinimaWath commented on 6-module/3-task/index.js
> +      inner.append(slideHTML);
Создание можно упростить, тем что в inner сразу вставлять строку, через шаблонные строки:
```
let carousel = createElement(`
      <div class="carousel">
        <div class="carousel__arrow carousel__arrow_right">
          <img src="../../assets/images/icons/angle-icon.svg" alt="icon">
        </div>
        <div class="carousel__arrow carousel__arrow_left">
          <img src="../../assets/images/icons/angle-left-icon.svg" alt="icon">
        </div>
        <div class="carousel__inner">
          ${slides.map((slide) => this.createSlideTemplate(slide))}
        </div>
      </div>
    `)
```

2022-05-13 20:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-14 10:13 UTC, SinimaWath approved these changes

2022-05-14 10:13 UTC, merged